apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conclave-minimal-workspace
spec:
  storageClassName: csi-rbd-safe
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
