apiVersion: v1
kind: Secret
metadata:
  name: conclave-minimal-env
type: Opaque
stringData:
  EXTERNAL_MATRIX_URL: ""
  EXTERNAL_PLANKA_URL: ""
  EXTERNAL_OLLAMA_URL: ""
  EXTERNAL_HOSTNAME: ""
  TZ: "UTC"
  CONCLAVE_ADMIN_PASSWORD: ""
  SSH_AUTHORIZED_KEYS: ""
