apiVersion: v1
kind: Service
metadata:
  name: conclave-minimal
spec:
  type: NodePort
  selector:
    app: conclave-minimal
  ports:
    - name: nginx
      port: 8888
      targetPort: 8888
    - name: ssh
      port: 22
      targetPort: 22
    - name: neko
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: neko-tcpmux
      port: 30181
      targetPort: 30181
      nodePort: 30181
    - name: ttyd
      port: 7681
      targetPort: 7681
    - name: chromadb
      port: 8000
      targetPort: 8000
