database:
  name: psycopg2
  args:
    host: 127.0.0.1
    database: synapse
    user: synapse
    password: PLACEHOLDER
    cp_min: 5
    cp_max: 10

media_store_path: "/workspace/data/synapse/media_store"
enable_registration: false

listeners:
  - port: 8008
    type: http
    resources:
      - names: [client, federation]
